"""FEAT: initial migration added to capture all the current models

Revision ID: 179b2062e0f4
Revises: 
Create Date: 2026-05-16 17:01:43.888628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179b2062e0f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_links_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('social_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_links_user_id'))

    # ### end Alembic commands ###
